class FastAPIHelperError(Exception): ...


class IngestError(FastAPIHelperError): ...


class RetrievalError(FastAPIHelperError): ...


class GenerationError(FastAPIHelperError): ...


class RateLimitError(FastAPIHelperError): ...


class ConfigError(FastAPIHelperError): ...
